#! /bin/sh

set -e

if [ -x /etc/init.d/umountnfs-alternative.sh ]; then
  if [ -x /usr/sbin/update-rc.d ]; then
    update-rc.d umountnfs-alternative.sh remove >/dev/null 2>&1
    update-rc.d umountnfs-alternative.sh defaults >/dev/null 2>&1
  fi
fi

##fix mx-tools menu files (mx 21 and older)
for i in $(find /home/ -wholename "*.config/menus/applications-merged/mx-tools.menu"); do 
	sed -i 's/MX-Tools/mx-tools/' "$i"
done


exit 0
