#! /bin/sh

set -e

if [ -x /etc/init.d/umountnfs-alternative.sh ]; then
  if [ -x /usr/sbin/update-rc.d ]; then
    update-rc.d umountnfs-alternative.sh remove >/dev/null 2>&1
    update-rc.d umountnfs-alternative.sh defaults >/dev/null 2>&1
  fi
fi

if [ -e  /etc/polkit-1/localauthority.conf.d/52-force-root-for-admin-auth.conf ]; then
	rm /etc/polkit-1/localauthority.conf.d/52-force-root-for-admin-auth.conf
fi

if [ -e /etc/lightdm/lightdm.conf ]; then
	sed -i "s,usr/local/bin/early-bg,usr/bin/early-bg," /etc/lightdm/lightdm.conf	
fi

#leave a symlink to the menu icon if callout exists in home folder
test=$(find /home/*/.config -type f -exec grep -l '/usr/local/share/icons/mxfcelogo-rounded.png' {} +)
if [ -z "$test" ]; then
	mkdir -p /usr/local/share/icons /usr/share/icons/mxfcelogo-rounded.png
	ln -nfs /usr/share/icons/mxfcelogo-rounded.png /usr/local/share/icons/mxfcelogo-rounded.png
fi

exit 0
